

ifndef CXX
    $(info "CXX is undefined.")
else
    $(info "CXX is $(CXX).")
endif

ifndef SOMETHING
    $(info "SOMETHING is undefined.")
else
    $(info "SOMETHING is $(SOMETHING).")
endif

.PHONY : all test

all :
	@echo "This all option!"

test :
	@echo "This test option!"
